### ISSUE TITLE
GetSequencePointMapping() throws Argument Exception

### ISSUE THREAD

**Issue by MNie** [jbevain/cecil#425] opened 2017-06-22 21:06 UTC
It looks like GetSequencePointMapping method ([line 675 or 682](cecil/Mono.Cecil.Cil/Symbols.cs)) tries to add a duplicate to a dictionary what results with a lock on an exe file.
Issue: [Expecto.Adapter](https://github.com/adamchester/expecto-adapter/issues/17)
Steps to reproduce:
1. Create/Open F# project in Visual Studio
2. Install Expecto ( > 5.0) and Adapter (> 5.0)
3. run tests several times 
4. update/reinstall packages related to Expecto
5. try to run specs

@adamchester

**Comment by jbevain** [comment] 2017-06-22 22:45
Thanks for reporting this. I'll need an exe and a pdb which reproduces the issue to diagnose the best fix.

**Comment by MNie** [comment] 2017-06-23 14:49
[Here](https://github.com/MNie/MonoCecil425) You are :)
I also noticed that if project with specs is set to Console Application everything is correct. If it set to Class library this error occurs.

@jbevain

**Comment by jbevain** [comment] 2017-06-23 16:59
That's very curious! Thanks for the repro, I'll have a look!

**Comment by MNie** [comment] 2017-07-02 09:32
Hi @jbevain!
How things are going on? Any information?

**Comment by SimonCropp** [comment] 2017-07-02 09:34
I think jb is travelling at the moment

**Comment by jbevain** [comment] 2017-07-19 00:08
I can't reproduce the issue with the binaries you provided. There's no method in ConsoleApplication.dll for which GetSequencePointMapping is throwing.

**Comment by jbevain** [comment] 2017-07-20 01:01
Closing this for now. Feel free to re-open with a repro.

**Closed by jbevain** 2017-07-20 01:01 UTC

**Comment by alex-bogomaz** [comment] 2017-09-08 10:45
Hello @jbevain . 
Please look into this issue once again.
Here is the binary on which this issue is reproduced:
https://github.com/alex-bogomaz/ExpectoAdapterCecilIssue/blob/master/ExpectoAdapterCecilIssue/bin/Debug/ExpectoAdapterCecilIssue.dll .

Following code: 
```csharp
var readerParams = new ReaderParameters { ReadSymbols = true, InMemory = true };
var moduleDefinition = ModuleDefinition.ReadModule(@"D:\GitHub\alex-bogomaz\ExpectoAdapterCecilIssue\ExpectoAdapterCecilIssue\bin\Debug\ExpectoAdapterCecilIssue.dll", readerParams);
var types = moduleDefinition.GetTypes();

foreach (var t in types)
{
    foreach (var m in t.GetMethods())
    {
         var s = m.DebugInformation.GetSequencePointMapping();
    }
}
```
fails with exception:
```System.ArgumentException occurred
  HResult=0x80070057
  Message=An item with the same key has already been added.
  Source=mscorlib
  StackTrace:
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Mono.Cecil.Cil.MethodDebugInformation.GetSequencePointMapping()
   at ConsoleApp1.Program.Main(String[] args) in D:\My\Projects\PSlogger-master\ConsoleApp1\Program.cs:line 25
```
Erroneous MethodDefinition is:
``` 
Microsoft.FSharp.Core.Unit 
ExpectoAdapterCecilIssue.Tests/equality@16::Invoke(Microsoft.FSharp.Core.Unit)}
```
Software version:
```xml
<package id="Mono.Cecil" version="0.10.0-beta6" targetFramework="net461" />
```
Related ExpectoAdapter issue:
https://github.com/adamchester/expecto-adapter/issues/28

**Comment by jbevain** [comment] 2017-09-08 17:58
@alex-bogomaz thanks for the repro!

**Comment by otto-gebb** [comment] 2017-11-03 11:27
@jbevain  Can we get a NuGet package with this fix? Expecto VS adapter doesn't work without it.
