### ISSUE TITLE
Build for .net core

### ISSUE THREAD

**Issue by Khhs167** [jbevain/cecil#759] opened 2021-05-30 08:07 UTC
Hi!  I am a new user to cecil and i am trying to get a hello world program up and running. It builds for framework and not core(wich i am not a big fan of) and therefore it references System.Private.CoreLib instead of mscorlib.dll. Now it also cannot find mscorlib.dll, do anyone have any idea?

**Comment by jbevain** [comment] 2021-06-22 21:52
Hi,

It's hard to know exactly what the issue is here. I'm going to close this as I'm afraid I can't help.

Feel free to add more details: show some code, what the error is, and we'll re-open this.

**Closed by jbevain** 2021-06-22 21:52 UTC
