### ISSUE TITLE
InterfaceImpl custom attributes are not exposed

### ISSUE THREAD

**Issue by ignas2** [jbevain/cecil#246] opened 2015-11-02 13:49 UTC
Custom attributes can be applied on interfaces a type implements explicitly. That's not allowed in C# but is in CLI specs. Sure, it's not very common but can be found in Windows Metadata assemblies. One such example is Windows.Foundation.Metadata.DefaultAttribute.

I have added support for this feature in my branch (https://github.com/ignas2/cecil/tree/ifaceimplca). However it's not backwards compatible. At the moment TypeDefinition exposes interfaces as a collection of TypeReferences. My solution is to add a new type 'Interface' that exposes InterfaceType property and collection of CustomAttributes. What do you think? Could we come up with a smarter implementation? I'm happy to work on this.

**Comment by jbevain** [comment] 2015-11-05 16:48
Hello Ignas,

Thanks for raising the issue, that's indeed something I have noted.

Note that the issue is not specific to interface implementations, as a CustomAttr record can target many different types of tables. Windows Metadata also uses custom attributes on TypeRef for instance.

As you noted, your suggested change is very much a breaking change :)

My initial thoughts was to expose methods on ModuleDefinition to retrieve different collections of custom attributes that are not exposed.

**Comment by ignas2** [comment] 2015-11-05 17:56
That would definitely work but it doesn't fit nicely with the reset of APIs. If I didn't know better I would be confused myself why I need to access certain attributes in different ways. So I'd rather see a breaking change but this is still better than no access at all.

**Comment by ignas2** [comment] 2015-11-18 19:33
Do you have an example where custom attribute is applied to type reference? I can create one myself with IL but I'd like to see a real world case.

**Comment by jbevain** [comment] 2016-07-15 04:19
Merged in master.

**Closed by jbevain** 2016-07-15 04:19 UTC
