### ISSUE TITLE
Support for AssemblyFileVersion and other PE header fields

### ISSUE THREAD

**Issue by asbjornu** [jbevain/cecil#208] opened 2015-03-17 10:46 UTC
Currently, adding `AssemblyFileVersionAttribute`, `AssemblyCopyrightAttribute` and other attributes that affect the PE header of an MSBuild generated `.dll` file (as can be inspected in the "Properties" dialog in Windows Explorer), have no effect in Cecil. I can see that [this was discussed in September 2006 on mono-devel-list](http://lists.ximian.com/pipermail/mono-devel-list/2006-September/020659.html) and that probably led to the current implementation that preserves roundtripping the header to an existing assembly, but not for assemblies generated by Cecil.

I've confirmed this and seen that loading an MSBuild generated `.dll` file with the PE header in place, modifying it and the writing it out to disk with Cecil, leaves the PE header intact. I've tried to study Cecil's source code to see how this is possible, but haven't come up with any good answers yet. I hoped to find that Cecil had some internal support for reading and writing these headers, but just had that code missing when generating an entirely new assembly. I made no such find, though.

Ultimately, what I'd love to do, is to add these attributes to any assembly written to disk by Cecil, no matter if the assembly is all generated by Cecil or a modification of an existing assembly. I'd love to provide a pull request if I were given a pointer on where to fix this. Thanks!

**Comment by SimonCropp** [comment] 2015-03-17 10:51
so similar to this https://github.com/gluck/cecil/commit/7a4cdab9f94f7065ec741e230d7a82c6819a92db  ?

**Comment by jbevain** [comment] 2015-03-17 10:53
Those are «fake» attributes. They're used by the compiler to generate win32 resources.

@SimonCropp yes, except that this particular information is at a higher level, as you need to know how to read the resource entry.

**Comment by jbevain** [comment] 2015-03-17 10:54
This is basically a dupe of #3 :)

**Comment by asbjornu** [comment] 2015-03-17 11:00
@jbevain Great. I had a look at that, but didn't realize that you were talking about the same thing as "PE header" wasn't mentioned anywhere. :smile:

**Comment by jbevain** [comment] 2015-03-17 11:27
Yeah those are not stored in the PE header :)
They're win32 resources, stored in the .rsrc section.

**Comment by asbjornu** [comment] 2015-03-17 12:44
Aha. This can just be closed then, I guess. :)

**Closed** 2015-03-17 12:44 UTC
