### ISSUE TITLE
Using package breaks VS2012 watch window symbol evaluation

### ISSUE THREAD

**Issue by blairstark** [jbevain/cecil#137] opened 2013-08-02 06:09 UTC
I found this issue using the Fody/PropertyChanged nugget package. 
Simon believes this is an issue with Cecil.

I wonder if this is the same as 

https://github.com/jbevain/cecil/issues/90 

### Steps to reproduce

1. create new console app project.
2. put a breakpoint on first curly brace of the Main method
3. run app
4. open watch window.
5. add this watch: `new List<string>()` observed result: Count = 0
6. Terminate the app
7. Now use NuGet,exe to add reference to PropertyChanged.Fody
8. run the app again to the breakpoint
9. watch evaluation is now: `The type or namespace name 'List' is not valid in this scope`

yes I know you can get it by fully qualifying, `System.Collections.Generic.List<string>`

but things are still broken

### Another example

put this in the watch window

    new System.Collections.Generic.List<string>().OfType<string>()

expected evaluation:

    {System.Linq.Enumerable.OfTypeIteratorList<string>}

observed:

    ` 'System.Collections.Generic.List<string>' does not contain a definition for 'OfType' and no extension method 
    'OfType' accepting a first argument of type 'System.Collections.Generic.List<string>' could be found (are you 
    missing a using directive or an assembly reference?) `

**Comment by jbevain** [comment] 2015-03-20 21:34
Duplicate of #90.

**Closed by jbevain** 2015-03-20 21:34 UTC
